config/routes.rb
Rails.application.routes.draw do
   devise_for :users
   
   root 'pages#index'

   resources :tutorials do 
      resources :reviews
   end

end

app/models/admin.rb
class Admin < ApplicationRecord
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tutorials
end

app/models/episode.rb
class Episode < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
   belongs_to :user
   belongs_to :tutorial
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :episode
  has_many :reviews

  has_attached_file :tutorial_img, styles: { tutorial_index: "700x300>", tutorial_show: "700x300>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :tutorial_img, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :tutorials
  has_many :reviews
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :store_current_location, :unless => :devise_controller?
  helper_method :logged_in?

  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be looged in to perform that action"
      redirect_to root_path
    end
  end

  def requier_admin_user
    if current_user.nil?
      flash[:danger] = "You must be looged in as admin to perform that action"
      redirect_to root_path
    elsif !current_user.admin?
      flash[:danger] = "You must be looged in as admin to perform that action"
      redirect_to root_path
    end
  end

  private

  def store_current_location
    store_location_for(:user, request.url)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_tutorial
  before_action :find_review, only: [:edit, :update, :destroy]

  def new
    @review = Review.new
  end

  def create
    
    @review = Review.new(review_params)
    @review.tutorial_id = @tutorial.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to tutorial_path(@tutorial)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to tutorial_path(@tutorial)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to tutorial_path(@tutorial)
  end

  private

  def review_params
    params.require(:review).permit(:comment)
  end

  def find_tutorial
    @tutorial = Tutorial.find(params[:tutorial_id])
  end

  def find_review
    @review = Review.find(params[:id])
  end

end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController

  before_action :find_params, only: [:show, :edit, :update, :destroy]
  before_action :requier_admin_user, except: [:index, :show]
  #before_filter :authenticate_admin!


  def index
    @tutorials = Tutorial.all
  end

  def new
    @tutorial = Tutorial.new
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def create
    @tutorial = current_user.tutorials.build(tutorial_params)
    @tutorial.category_id = params[:category_id]

    if @tutorial.save
      redirect_to @tutorial
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def update
    @tutorial.category_id = params[:category_id]
    if @tutorial.update(tutorial_params)
      redirect_to @tutorial
    else
      render 'edit'
    end
  end

  def destroy
    if @tutorial.destroy
      redirect_to tutorials_path
    else
      render 'show'
    end
  end

  private

    def tutorial_params
      params.require(:tutorial).permit(:title, :content, :category_id, :tutorial_img, :episode_id)
    end

    def find_params
      @tutorial = Tutorial.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/layouts/_footer.html.erb
<section id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <p>&copy; Copyright 2016 Mohsen Sadeghbeigi - All Rights Reserved</p>
      </div>
      <div class="col-md-6">
        <div align="right">
          <%= fa_icon "facebook-square", class: "fa-2x social" %>
          <%= fa_icon "twitter-square", class: "fa-2x social" %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="Navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="               navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Learn to CODE', root_path, class: 'navbar-brand' %>
      <!-- <a class="navbar-brand" href="#">
        <div class="logo">
          <img src="/assets/logo.png">
        </div>

      </a> -->
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Tutorials', tutorials_path, class: "link" %></li>
        <% if logged_in? && current_user.admin? %>
          <li><%= link_to 'Add Tutorial', new_tutorial_path, class: "link" %></li>
        <% end %>
        <% if !logged_in? %>
          <li><%= link_to 'Log In', new_user_session_path, class: 'link' %></li>
        <% end %>

        <% if logged_in? && user_signed_in? %> 
          <li class="drop-down">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete%></li>
            </ul>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<!--  
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Learn to CODE', root_path, class: "navbar-brand" %>
    </div>

    <ul class="nav navbar-nav">
      <li><%= link_to 'Home', tutorials_path %></li> 
      <% if logged_in? && current_user.admin? %>           
        <li><%= link_to 'Add Tutorial', new_tutorial_path %></li>
      <% end %>
    </ul>


    
    <ul class="navbar navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <%= current_user.email %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <%= link_to 'Log In', new_user_session_path, class: "btn btn-primary" %>
        <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-info" %>
      <% end %>
    </ul>
    
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Category <span class="caret"></span></a>

        <ul class="dropdown-menu" role="menu">
          <% Category.all.each do |category| %>
            <li class="<%= 'active' if params[:category] == category.name %>">
              <%= link_to category.name, tutorials_path(category: category.name), class: "link" %>
            </li>
          <% end %>
        </ul>
      </li>
    </ul>
  </div>
</nav>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Test</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    
    <%= yield %>
    <!-- <%= debug(params) if Rails.env.development? %> -->
    <!-- FOOTER -->
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/pages/index.html.erb
<section id="hero">
  <div class="container">
    <div class="row">
      <h1><span class="colorize">New Way to Learn </span>Ruby on Rails</h1>      
      <div class="col-md-4 col-md-offset-4" align="center">
        <h2>Iprove your code skills in our tutorials</h2>
        <%= link_to 'Sign Up Today', new_user_registration_path, class: "btn btn-success button" %>
      </div>
    </div>
  </div>
</section>

<!-- WHAT WE DO -->
<section id="what-we-do">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div align="center">
          <%= fa_icon "code", class: "fa-5x icon" %>
        </div>
      </div>
      <div class="col-md-6">
        <h1 class="wwd-header">Learn how to code</h1>
        <p class="wwd-para"> Learn how to code in Ruby on Rails and how to deploy your application and how to style your web app and how to embed html with Ruby. </p>
      </div>
    </div>
  </div>
</section>
<section id="what-we-do-2">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1 class="wwd-header-2">Learn to deploy your app</h1>
        <p class="wwd-para-2"> Learn how to deploy your written app and how to merge that with most famoud Ruby on Rails deploymenet client, HEROKU </p>
      </div>
      <div class="col-md-6">
        <div align="center">
          <%= fa_icon "terminal", class: "fa-5x icon" %>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="what-we-do-2">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div align="center">
          <%= fa_icon "code-fork", class: "fa-5x icon-git" %>
        </div>
      </div>
      <div class="col-md-6">
        <h1 class="wwd-header">Learn git and github</h1>
        <p class="wwd-para"> Learn how to backup you code and make a repository from your code. Engage whit thousands of people of the world and share your Ruby on Rails skills.  </p>
      </div>
    </div>
  </div>
</section>

<!-- OUR COURSE -->
<section id="our-course">
  <div class="container">
    <h1>Our tutorials are avalable in Videos and Articles</h1>
    <div class="row">
      <div class="col-md-6">
        <div align="center">
          <%= fa_icon "video-camera", class: "fa-5x oc-icon" %>
        </div>
        <p>Watch tutorials with high quality and most responsive way</p>
      </div>
      <div class="col-md-6">
        <div align="center">        
          <%= fa_icon "file-text", class: "fa-5x oc-icon" %>
        </div>
        <p>Read our tutorials completely free and follow them to see what will happen on next lectures</p>
      </div>
    </div>
  </div>
</section>

<!-- FOOTER -->


<!-- 
<script>
  
  (function ($) {
    $(document).ready(function() {

        $(".navbar").show();
        $(function() {
          $(window).scroll(function() {
          if ($(this).scrollTop() > 700) {
            $(".navbar").slideUp("slow");
          } else {
            $(".navbar").slideDown('slow');
          }
        });
      });
    });

  }(jQuery));

</script>

 -->





















 

app/views/reviews/_form.html.erb
<%= render 'shared/errors', obj: @tutorial %>

<%= form_for ([@tutorial, @tutorial.reviews.build]) do |f| %>
  <div class="comment-form">
    <%= f.text_area :comment %>
  </div>
  <%= f.submit :submit, class: "btn-custom2" %>
<% end %>

app/views/reviews/edit.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="edit-review-form">
    <h1>Edit Review</h1>
    <%= form_for ([@tutorial, @review]) do |f| %>
      <div class="comment-form">
        <%= f.text_area :comment %>
      </div>
      <%= f.submit :submit, class: "btn-custom" %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="new-review-form">
    <h1>Post Review </h1>
    <%= render 'form' %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being save
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/tutorials/_form.html.erb
<%= render 'shared/errors', obj: @tutorial %>
<section id="new-tutorial">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for @tutorial do |f| %>
          <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select Category") %>
          <br>
          <%= f.file_field :tutorial_img %>

          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_area :content , class: "form-control form-input" %>
          </div>
          <%= f.submit :submit, class: 'btn btn-primary btn-lg' %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/tutorials/edit.html.erb
<%= render 'shared/errors', obj: @tutorial %>

<section id="new-tutorial">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for @tutorial, html: {multipart: true} do |f| %>
          <%= f.select :category_id, @categories %>
          <%= f.file_field :tutorial_img %>

          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_area :content , class: "form-control form-input" %>
          </div>
          <%= f.submit 'Create', class: 'btn btn-primary btn-lg' %>
          <%= link_to 'Cancel', tutorial_path(@tutorial), class: "btn-link" %>
        <% end %>

      </div>
    </div>
  </div>
</section>

app/views/tutorials/index.html.erb
<section id="tutorials">
  <h1 class="current-category"><%= params[:category] %></h1>
  <% if @tutorials.count == 0 %>
    <h3>There are no tutorials in this category</h3>
  <% else %> 
    <div class="row">
      <% @tutorials.each do |tutorial| %>
        <div class="container">        
          <div class="col-md-6">        
            <%= image_tag tutorial.tutorial_img.url(:tutorial_index), class: "img-responsive show-img" %>
          </div>
          <div class="col-md-6">              
            <h2><%= truncate(tutorial.content, length: 300) %></h2>
            <%= link_to 'Read More', tutorial_path(tutorial), class: "btn-info" %>
          </div>
        </div>
        <hr> 
      <% end %>
    </div>
  <% end %> <!-- END ELSE -->
</section>

app/views/tutorials/new.html.erb
<%= render 'form' %>

app/views/tutorials/show.html.erb
<%= render 'shared/errors', obj: @tutorial %>
<section id="show-tutorial">
  <div class="container">
    <div class="row">
      <div class="col-md-12" align="center">
        <div id=<%= @tutorial.episode.aparat_id %>><script type="text/JavaScript" src="https://www.aparat.com/embed/<%= @tutorial.episode.aparat_embed %>&data[responsive]=yes"></script></div>
      </div>
    </div>
  </div>

  <!-- DOWNLOAD BUTTON ADDING -->
  <div class="container">
    <div class="row">
      <div class="col-md-10" align="center">
        
        <% if logged_in? %>
          <%= link_to 'Download project', root_path, class: "btn-info" %>
        <% else %>
          <h4>You need to be a user to download this project.<%= link_to 'Sign Up', new_user_registration_path, class: 'btn-info' %></h4>
        <% end %>
      </div>
    </div>
  </div>
  <hr>
  <div class="container">
    <div class="row">
      <div class="col-md-10">
        <div class="tutorial-info">
          <h2 class="tutorial-title"><%= @tutorial.title %></h2>
          <span class="tutorial-category">category: <em><%= @tutorial.category.name %></em></span><hr>
          <p class="tutorial-decs"><%= simple_format(@tutorial.content) %></p>
          <div class="links btn-group">
            <div class="container">
              <% if logged_in? && current_user.admin? %>
                <%= link_to 'Edit this tutorial', edit_tutorial_path(@tutorial), class: 'btn btn-xs btn-primary' %>
                <%= link_to 'Delete this tutorial', tutorial_path(@tutorial), method: :delete, data: { confirm: "Are you sure you want to delete this tutorial?" }, class: 'btn btn-xs btn-danger' %>
              <% end %>
            </div>
          </div>
        </div>
        <hr>
      </div>
    </div>
  </div>
</section>